### ISSUE TITLE
Version conflict between Matplotlib et numpy

### ISSUE THREAD

**Issue by EricFournier3** [BCCDC-PHL/fluviewer-nf#40]
Hi,

when I run the following command

`nextflow run BCCDC-PHL/fluviewer-nf -r v0.3.0 -profile conda --cache /data/devel/fluviewer/conda --fastq_input /data/devel/fluviewer/fastq --db /data/devel/fluviewer/db/FluViewer_db_v_0_1_8.fa --outdir /data/devel/fluviewer/out`

fluviewer.nf produces the following Import Error

Traceback (most recent call last):
  File "/data/devel/fluviewer/conda/fluviewer-nf-FluViewer-98a3cd0cef99579de0b5ca640a2e19df/bin/fluviewer", line 5, in <module>
    from fluviewer.fluviewer import main
  File "/data/devel/fluviewer/conda/fluviewer-nf-FluViewer-98a3cd0cef99579de0b5ca640a2e19df/lib/python3.9/site-packages/fluviewer/fluviewer.py", line 23, in <module>
    from . import plots
  File "/data/devel/fluviewer/conda/fluviewer-nf-FluViewer-98a3cd0cef99579de0b5ca640a2e19df/lib/python3.9/site-packages/fluviewer/plots.py", line 9, in <module>
    import seaborn as sb
  File "/data/devel/fluviewer/conda/fluviewer-nf-FluViewer-98a3cd0cef99579de0b5ca640a2e19df/lib/python3.9/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "/data/devel/fluviewer/conda/fluviewer-nf-FluViewer-98a3cd0cef99579de0b5ca640a2e19df/lib/python3.9/site-packages/seaborn/rcmod.py", line 3, in <module>
    import matplotlib as mpl
  File "/data/devel/fluviewer/conda/fluviewer-nf-FluViewer-98a3cd0cef99579de0b5ca640a2e19df/lib/python3.9/site-packages/matplotlib/__init__.py", line 263, in <module>
    _check_versions()
  File "/data/devel/fluviewer/conda/fluviewer-nf-FluViewer-98a3cd0cef99579de0b5ca640a2e19df/lib/python3.9/site-packages/matplotlib/__init__.py", line 259, in _check_versions
    raise ImportError(f"Matplotlib requires {modname}>={minver}; "
**ImportError: Matplotlib requires numpy>=1.23; you have 1.22.4**

Yet, as you can see in my fluviewer-nf-FluViewer-98a3cd0cef99579de0b5ca640a2e19df conda environment the version of numpy is 1.26.4 (not 1.22.4)

```
(base) [site-packages]$ pwd
/data/devel/fluviewer/conda/fluviewer-nf-FluViewer-98a3cd0cef99579de0b5ca640a2e19df/lib/python3.9/site-packages
(base) [site-packages]$ ls -d numpy*/
numpy/  numpy-1.26.4.dist-info/
```

Do you have any idea regarding this issue?

Thanks
Eric

**Comment by EricFournier3** [comment]
I finally found the cause. I will close this issue
